# Generated by Django 2.0.5 on 2018-06-09 06:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the location name', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Phenome',
            fields=[
                ('ENAR', models.CharField(help_text='ENAR ID', max_length=10, verbose_name='ENAR ID')),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('meas', models.FileField(upload_to='', verbose_name='Measurements')),
                ('ID', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular Phenome across whole bank', primary_key=True, serialize=False)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databank.Location')),
            ],
            options={
                'ordering': ['ID', 'ENAR', 'date', 'species', 'location'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the species name', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='phenome',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databank.Species'),
        ),
    ]
