# Generated by Django 2.0.5 on 2018-06-28 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0002_auto_20180628_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='databank.Property_base'),
        ),
        migrations.AlterField(
            model_name='property',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='databank.Individual'),
        ),
        migrations.AlterField(
            model_name='property_base',
            name='type',
            field=models.CharField(choices=[('N', 'Node'), ('T', 'Text'), ('F', 'Number'), ('C', 'Choice')], max_length=1),
        ),
    ]
