# Generated by Django 2.0.5 on 2018-06-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0003_auto_20180628_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='father',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='mother',
        ),
        migrations.AddField(
            model_name='individual',
            name='child',
            field=models.ManyToManyField(blank=True, null=True, related_name='children', to='databank.Individual'),
        ),
        migrations.AddField(
            model_name='individual',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, related_name='parents', to='databank.Individual'),
        ),
    ]
