# Generated by Django 2.0.5 on 2018-06-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0004_auto_20180628_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='child',
            field=models.ManyToManyField(blank=True, related_name='children', to='databank.Individual'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='parents', to='databank.Individual'),
        ),
    ]
