# Generated by Django 2.0.5 on 2018-07-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0005_auto_20180628_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='Name',
            field=models.CharField(default='Name', help_text='Name', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
