# Generated by Django 2.0.5 on 2018-07-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='numVal',
            field=models.FloatField(help_text='Enter the value of the numerical option', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='textVal',
            field=models.CharField(help_text='Enter the minimal value of the text option', max_length=200, null=True),
        ),
    ]
