# Generated by Django 2.0.5 on 2018-07-03 16:21

import databank.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('databank', '0008_auto_20180702_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=databank.models.upl_file_name, verbose_name='Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='individual',
            name='child',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='image',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='meas',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='parent',
        ),
        migrations.AddField(
            model_name='individual',
            name='owner',
            field=models.ForeignKey(help_text='Assigned User', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individual',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='databank.Individual'),
        ),
        migrations.AddField(
            model_name='subspecies',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='databank.Species'),
        ),
        migrations.AlterField(
            model_name='property',
            name='ID',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular property across whole bank', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='image',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='databank.Individual'),
        ),
    ]
