# Generated by Django 2.0.5 on 2018-07-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0009_auto_20180703_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='date',
            field=models.DateField(help_text='Birth Date', null=True),
        ),
    ]
