# Generated by Django 2.0.5 on 2018-07-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0012_auto_20180704_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='ID',
            new_name='UID',
        ),
    ]
