# Generated by Django 2.0.5 on 2018-07-04 10:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0017_auto_20180704_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='UNID',
            field=models.UUIDField(default=uuid.uuid1, help_text='Unique ID for this particular image across whole bank', primary_key=True, serialize=False),
        ),
    ]
