# Generated by Django 2.0.7 on 2018-07-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0019_property_base_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['parent__parent', 'parent__name']},
        ),
    ]
