# Generated by Django 2.0.7 on 2018-07-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0020_auto_20180706_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_base',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='location',
            field=models.CharField(help_text='Birth Location', max_length=100, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='property_base',
            name='maxVal',
            field=models.FloatField(blank=True, help_text='Enter the maximal value of the numerical option', null=True),
        ),
        migrations.AlterField(
            model_name='property_base',
            name='minVal',
            field=models.FloatField(blank=True, help_text='Enter the minimal value of the numerical option', null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
