# Generated by Django 2.0.7 on 2018-07-24 10:10

import databank.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0021_auto_20180711_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='image',
            field=models.ImageField(null=True, upload_to=databank.models.upl_file_name, verbose_name='Image'),
        ),
    ]
